---
- name: Gather facts
  hosts: Group1
  become: false
  become_method: sudo
  gather_facts: false
  connection: local
  roles:
      - tower_network
  tasks:
    - vyos_facts:
        gather_subset: all
