---
- name: Gather facts
  hosts: Group1
  become: false
  become_method: sudo
  gather_facts: false
  connection: network_cli
  tasks:
    - vyos_facts:
        gather_subset: all
    - debug:
        msg: "{{ansible_net_neighbors}}"

