---
- name: Gather facts
  hosts: Switches
  become: false
  become_method: sudo
  gather_facts: false
  connection: local
  tasks:
    - name: Discover link connections
      vyos_facts:
        gather_subset: all
