---
- name: Transform topology information to host vars and group vars
  hosts: localhost
  gather_facts: false
  tasks:
      - include_vars:
            file: vars/provision.yml
      - requests_get:
            url: "http://{{server}}/network_ui/topology_yaml?topology_id={{topology_id}}"
            output: topology.yml
      - vagrant_ssh_config:
            output: ssh-config
      - convert_ssh_config_to_ansible_inventory2:
            data: topology.yml
            ssh_config: ssh-config
            output: hosts
      - add_ip_addresses:
            supernet: "{{supernet}}"
            subnet_size: "{{subnet_size}}"
            input: topology.yml
            output: topology.yml
      - lookup_set_value:
            input: topology.yml
            output: topology.yml
            lookup_path: Host2.eth1.ip_address
            set_path: processor
      - lookup_set_value:
            input: topology.yml
            output: topology.yml
            lookup_path: Host3.eth1.ip_address
            set_path: generator
      - generate_reachable:
            input: topology.yml
            output: ip_addresses.yml
      - add_router_id:
            input: topology.yml
            output: topology.yml
            router_id_range: "{{router_id_range}}"
      - generate_host_vars:
            host_vars_directory: host_vars
            data: topology.yml
      - generate_csvs:
            data: topology.yml
      - jinja:
            template: templates/nat_hosts_with_groups.j2
            context: topology.yml
            output: nat_hosts
      - local_shell:
            command: cp topology.yml group_vars/all
