---
- name: Fix the hostname
  hosts: all
  tasks:
  - name: Fix hostname
    become: true
    become_method: sudo
    hostname:
        name: "{{name}}"
  - name: Restart
    become: true
    become_method: sudo
    shell: sleep 5; reboot &
    async: 0
    poll: 0
  - local_action: "pause seconds=10"
  - name: Wait
    local_action: "wait_for host={{ ansible_host }} state=started port={{ansible_port}} delay=30 timeout=60"
