---
- name: Up all interfaces
  hosts: all
  become: true
  become_method: sudo
  gather_facts: false
  connection: local
  tasks:
    - debug:
        msg: "{{cli}}"
    - vyos_config:
        lines:
            - set service lldp
        provider: "{{cli}}"
    - vyos_facts:
        gather_subset: all
        provider: "{{cli}}"
