---
- name: Up all interfaces on switches
  hosts: Switches
  become: false
  become_method: sudo
  gather_facts: false
  connection: local
  tasks:
    - name: Enable LLDP
      vyos_config:
        lines:
            - set service lldp
    - name: Set IP address on interface
      vyos_config:
        lines:
            - "set interfaces ethernet {{item.name}} address '{{item.ip_address}}/{{item.subnet_prefixlen}}'"
      with_items: "{{interfaces}}"
      when: item.ip_address is defined
    - name: Gather link connection facts
      vyos_facts:
        gather_subset: all
- name: Up all interfaces on hosts
  hosts: Hosts
  become: true
  become_method: sudo
  gather_facts: false
  tasks:
      - name: Shut interface before reconfigure
        shell: "ifdown {{item.name}}"
        with_items: "{{interfaces}}"
      - name: Reconfigure interface with a static IP address
        template:
          src: templates/etc_network_interfaces
          dest: /etc/network/interfaces
          owner: root
          group: root
          mode: '0600'
      - name: Up interface
        shell: "ifup {{item.name}}"
        with_items: "{{interfaces}}"


