---
- name: Add machine credentials
  hosts: all
  gather_facts: false
  tasks:
  - name: Add ssh pub key
    authorized_key:
        user: vagrant
        state: present
        key: "{{ lookup('file', workspace + '/key.pub') }}"
