- name: Enable LLDP on hosts
  hosts: Hosts
  become: true
  become_method: sudo
  gather_facts: false
  tasks:
      - name: Update package cache
        apt:
          update_cache: yes
      - name: Install lldpd
        apt:
          name: lldpd
          state: present

