- name: Enable LLDP on hosts
  hosts: Hosts
  become: true
  become_method: sudo
  gather_facts: false
  tasks:
      - apt:
          update_cache: yes
      - apt:
          name: lldpd
          state: present

