---
- name: Break OSPF
  hosts: switch
  become: false
  become_method: sudo
  gather_facts: false
  connection: local
  tasks:
    - vyos_config:
        lines:
            - "delete protocols ospf"
