---
- name: Up all interfaces
  hosts: switch
  become: false
  become_method: sudo
  gather_facts: false
  connection: local
  tasks:
      - vyos_command:
          commands:
              - "/bin/ping -c 1 {{item.remote_ip_address}}"
          provider: "{{cli}}"
          wait_for:
              - "result[0] contains '1 packets transmitted, 1 received, 0% packet loss'"
          retries: 1
        with_items: "{{interfaces}}"
        when: item.remote_ip_address is defined
