---
- name: Up all interfaces
  hosts: Hosts
  become: false
  become_method: sudo
  gather_facts: false
  tasks:
      - include_vars:
          file: files/ip_addresses.yml
          name: reachable
      - debug:
          msg: "{{reachable.devices}}"
      - shell: "ping -c 1 {{item.ip_address}}"
        with_items: "{{reachable.devices}}"

