---
- name: Install pipeline demo application
  hosts: Hosts
  become: true
  become_method: sudo
  gather_facts: false
  tasks:
      - copy:
          src: files/pip.conf
          dest: /etc/pip.conf
      - copy:
          src: files/ez_setup.py
          dest: /home/vagrant/ez_setup.py
      - shell: python /home/vagrant/ez_setup.py
      - shell: easy_install pip
      - shell: pip install -i http://192.168.121.1:3040/ben/dev --trusted-host 192.168.121.1 zero_pipeline
- name: Start pipeline receivers
  hosts: Receivers
  tasks:
      - template:
          src: files/host1.yml
          dest: /home/vagrant/zero_pipeline.yml
      - shell: zero_pipeline receiver --daemonize
        args:
            chdir: /home/vagrant/
- name: Start pipeline processors
  hosts: Processors
  tasks:
      - template:
          src: files/host2.yml
          dest: /home/vagrant/zero_pipeline.yml
      - shell: zero_pipeline processor --daemonize
        args:
            chdir: /home/vagrant/
- name: Start pipeline generators
  hosts: Generators
  tasks:
      - template:
          src: files/host3.yml
          dest: /home/vagrant/zero_pipeline.yml
      - shell: zero_pipeline generator --daemonize
        args:
            chdir: /home/vagrant/

