---
- name: Configure Routing and Switching
  hosts: Switches
  become: false
  become_method: sudo
  gather_facts: false
  connection: local
  tasks:
    - include: ospf.yml
      with_items: "{{processes}}"
      when: item.name == 'OSPF'
