---
- name: Configure Routing and Switching
  hosts: Switches
  become: false
  become_method: sudo
  gather_facts: false
  connection: local
  tasks:
    - name: Load static variables
      include_vars:
        file: vars/provision.yml
    - name: Include OSPF if enabled
      include: ospf.yml
      with_items: "{{processes}}"
      when: item.name == 'OSPF'
