---
- name: Start VMs on hypervisor
  hosts: hypervisor
  gather_facts: false
  tasks:
      - ping:
      - name: Start VMs
        shell: "{{virtualenv}}/bin/ansible-playbook playbook/up.yml --extra-vars \"topology_id={{topology_id}} server={{server}}\""
        args:
          chdir: "{{workspace}}"
      - name: Install SSH Credentials
        shell: "{{virtualenv}}/bin/ansible-playbook -i hosts playbook/key.yml --extra-vars \"workspace={{workspace}}\""
        args:
          chdir: "{{workspace}}"
      - synchronize:
          mode: pull
          src: "{{workspace}}/host_vars"
          dest: .
      - synchronize:
          mode: pull
          src: "{{workspace}}/group_vars"
          dest: .
      - synchronize:
          mode: pull
          src: "{{workspace}}/nat_hosts"
          dest: files/
      - local_shell:
          command: "awx-manage inventory_import --source=./files/nat_hosts --inventory-id={{inventory_id}}"
          chdir: "playbook"
