---
- name: Start VMs on hypervisor
  hosts: hypervisor
  gather_facts: false
  tasks:
      - ping:
      - name: Start VMs
        shell: "/home/ben/env/vyos-topology/bin/ansible-playbook playbook/up.yml --extra-vars topology_id={{topology_id}}"
        args:
          chdir: /home/ben/git/vyos-topology
      - name: Install SSH Credentials
        shell: /home/ben/env/vyos-topology/bin/ansible-playbook -i hosts playbook/key.yml
        args:
          chdir: /home/ben/git/vyos-topology
      - synchronize:
          mode: pull
          src: /home/ben/git/vyos-topology/host_vars
          dest: .
      - synchronize:
          mode: pull
          src: /home/ben/git/vyos-topology/group_vars
          dest: .
      - synchronize:
          mode: pull
          src: /home/ben/git/vyos-topology/nat_hosts
          dest: files/
      - synchronize:
          mode: pull
          src: /home/ben/git/vyos-topology/ip_address.yml
          dest: files/
      - local_shell:
          command: "awx-manage inventory_import --source=./files/nat_hosts --inventory-id={{inventory_id}}"
          chdir: "playbook"
