---
- name: Transform topology data into host vars and group vars
  hosts: controller
  gather_facts: false
  tasks:
      - name: Generate host vars and group vars
        shell: "{{virtualenv}}/bin/ansible-playbook playbook/generate.yml --extra-vars \"topology_id={{topology_id}} server={{server}}\""
        args:
          chdir: "{{workspace}}"
      - name: Copy generate host vars
        synchronize:
          mode: pull
          src: "{{workspace}}/host_vars"
          dest: .
      - name: Copy generate group vars
        synchronize:
          mode: pull
          src: "{{workspace}}/group_vars"
          dest: .
      - name: Copy generated inventory file
        synchronize:
          mode: pull
          src: "{{workspace}}/nat_hosts"
          dest: files/
      - name: Copy generated IP addresses
        synchronize:
          mode: pull
          src: "{{workspace}}/ip_addresses.yml"
          dest: files/
      - name: Import generated host vars and group vars
        local_shell:
          command: "awx-manage inventory_import --source=./files/nat_hosts --inventory-id={{inventory_id}}"
          chdir: "playbook"
