---
- name: Create Topology Using Vagrant
  hosts: localhost
  gather_facts: false
  tasks:
      - requests_get:
            url: http://meganuke:8013/network_ui/topology_yaml?topology_id=144
            output: topology.yml
      - add_ports:
            range_start: 9100
            input: topology.yml
            output: topology.yml
      - jinja:
            template: templates/Vagrantfile.j2
            context: topology.yml
            output: Vagrantfile
      - generate_host_vars:
            data: topology.yml
            host_vars_directory: host_vars
      - vagrant_up:
      - vagrant_ssh_config:
            output: ssh-config
      - convert_ssh_config_to_ansible_inventory:
            ssh_config: ssh-config
            output: hosts
      - add_cli_connection:
            ssh_config: ssh-config
            input: topology.yml
            output: topology.yml
      - add_mgmt_ip:
            ssh_config: ssh-config
            input: topology.yml
            output: topology.yml
            nat_ip: '10.17.161.200'
            port_range_start: 10100
      - generate_host_vars:
            host_vars_directory: host_vars
            data: topology.yml
      - jinja:
            template: templates/iptables.j2
            context: topology.yml
            output: iptables.rules
      - jinja:
            template: templates/iptables_remove.j2
            context: topology.yml
            output: iptables_remove.rules
      - jinja:
            template: templates/nat_hosts.j2
            context: topology.yml
            output: nat_hosts
      - local_shell:
            command: chmod +x iptables.rules
      - local_shell:
            command: chmod +x iptables_remove.rules
      - local_shell:
            command: ./iptables.rules
      - local_shell:
            command: cp topology.yml group_vars/hosts
      - local_shell:
            command: git add topology.yml host_vars group_vars iptables.rules iptables_remove.rules
      - local_shell:
            command: git commit -m "Update inventory"
      - local_shell:
            command: git push
      - local_shell:
            command: ansible-playbook -i hosts playbook/key.yml
