---
- name: Update host vars from files on disk through the API
  hosts: tower
  gather_facts: false
  roles:
      - tower_network
  tasks:
      - update_host_vars:
          inventory_id: 2
          host_vars: playbook/host_vars/host_vars
