---
- name: Get a device using the tower network ui api
  hosts: tower
  gather_facts: false
  roles:
      - tower_network
  tasks:
    - range:
        start: 0
        end: 2000
        increment: 200
        var: leaf_range
    - range:
        start: 500
        end: 1500
        increment: 200
        var: spine_range
    - enumerate:
        list: "{{leaf_range}}"
        var: leaf_range
    - enumerate:
        list: "{{spine_range}}"
        var: spine_range
    - create_device:
        topology: 1
        name: "Leaf{{item.0}}"
        x: "{{item.1}}"
        y: 1000
        id: "{{item.1}}"
        type: switch
        var: new_device
      with_items:
          - "{{leaf_range}}"
      register: leaves
    - create_device:
        topology: 1
        name: "Spine{{item.0}}"
        x: "{{item.1}}"
        y: 500
        id: "{{item.1}}"
        type: switch
        var: new_device
      with_items:
          - "{{spine_range}}"
      register: spines
    - map:
        list: "{{leaves.results}}"
        attribute: ansible_facts/new_device
        var: leaves2
    - map:
        list: "{{spines.results}}"
        attribute: ansible_facts/new_device
        var: spines2
    - debug:
        msg: "leaves {{leaves2}}"
    - debug:
        msg: "spines {{spines2}}"
