---
- name: Get a device using the tower network ui api
  hosts: tower
  gather_facts: false
  roles:
      - network_demo
  tasks:
    - get_device:
        device_id: 307
        var: device1
    - debug:
        msg: "device1 {{device1}}"
    - debug:
        msg: "device1.name {{device1.name}}"
    - list_device:
        var: devices
    - debug:
        msg: "devices {{devices}}"
    - create_device:
        topology: 21
        name: playbook_created
        x: 0
        y: 0
        id: 78
        type: router
        var: new_device
    - debug:
        msg: "new_device {{new_device}}"
    - update_device:
        device_id: "{{new_device.device_id}}"
        x: 1000
        y: 1000
        var: new_device2
    - debug:
        msg: "new_device2 {{new_device2}}"
    - create_device:
        topology: 21
        name: should_be_deleted
        x: 0
        y: 0
        id: 66
        type: router
        var: to_delete
    - delete_device:
        device_id: "{{to_delete.device_id}}"
